// RUN: triton-opt %s --triton-rewrite-tensor-descriptor-to-pointer --canonicalize --cse --mlir-print-debuginfo --split-input-file | FileCheck %s --implicit-check-not \!tt.tensordesc

module {
  tt.func public @load(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: i32, %arg2: i32) -> (tensor<128x128xf32>) {
    %c1_i64 = arith.constant 1 : i64
    %c256_i64 = arith.constant 256 : i64
    %c0_i32 = arith.constant 0 : i32
    %c128_i32 = arith.constant 128 : i32
    %c256_i32 = arith.constant 256 : i32
    %0 = tt.make_tensor_descriptor %arg0, [%c256_i32, %c256_i32], [%c1_i64, %c256_i64] {order = array<i32: 0>} : <f32>, <128x128xf32>
    %3 = tt.descriptor_load %0[%arg1, %arg2] : !tt.tensordesc<128x128xf32> -> tensor<128x128xf32>
    tt.return %3 : tensor<128x128xf32>
  }
}

// CHECK-LABEL: @load
// CHECK-SAME: %[[ARG0:[^:]*]]
// CHECK-SAME: %[[ARG1:[^:]*]]
// CHECK-SAME: %[[ARG2:[^:]*]]
// CHECK-DAG: %[[CST:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32>
// CHECK-DAG: %[[CST0:.*]] = arith.constant dense<0> : tensor<1x128xi64>
// CHECK-DAG: %[[CST1:.*]] = arith.constant dense<256> : tensor<128x1xi64>
// CHECK-DAG: %[[CST2:.*]] = arith.constant dense<0> : tensor<128x1xi64>
// CHECK-DAG: %[[CST3:.*]] = arith.constant dense<256> : tensor<1x128xi64>

// CHECK-DAG: %[[VAL0:.*]] = arith.extsi %[[ARG1]] : i32 to i64
// CHECK-DAG: %[[VAL1:.*]] = arith.extsi %[[ARG2]] : i32 to i64
// CHECK-DAG: %[[VAL2:.*]] = tt.splat %[[ARG0]] :
// CHECK-DAG: %[[VAL3:.*]] = tt.splat %[[VAL0]] :
// CHECK-DAG: %[[VAL4:.*]] = tt.make_range {end = 128 : i32, start = 0 : i32}
// CHECK-DAG: %[[VAL5:.*]] = arith.extsi %[[VAL4]] :
// CHECK-DAG: %[[VAL6:.*]] = arith.addi %[[VAL3]], %[[VAL5]] :
// CHECK-DAG: %[[VAL7:.*]] = tt.reshape %[[VAL6]]
// CHECK-DAG: %[[VAL8:.*]] = tt.broadcast %[[VAL7]] : tensor<128x1xi64> -> tensor<128x128xi64>
// CHECK-DAG: %[[VAL9:.*]] = tt.addptr %[[VAL2]], %[[VAL8]] :
// CHECK-DAG: %[[VAL10:.*]] = tt.splat %[[VAL1]] :
// CHECK-DAG: %[[VAL11:.*]] = arith.addi %[[VAL10]], %[[VAL5]] :
// CHECK-DAG: %[[VAL12:.*]] = tt.reshape %[[VAL11]]
// CHECK-DAG: %[[VAL13:.*]] = arith.muli %[[VAL12]], %[[CST3]] :
// CHECK-DAG: %[[VAL14:.*]] = tt.broadcast %[[VAL13]] : tensor<1x128xi64> -> tensor<128x128xi64>
// CHECK-DAG: %[[VAL15:.*]] = tt.addptr %[[VAL9]], %[[VAL14]] :

// CHECK-DAG: %[[VAL16:.*]] = arith.cmpi sge, %[[VAL7]], %[[CST2]]
// CHECK-DAG: %[[VAL17:.*]] = arith.cmpi slt, %[[VAL7]], %[[CST1]]
// CHECK-DAG: %[[VAL18:.*]] = arith.andi %[[VAL16]], %[[VAL17]]
// CHECK-DAG: %[[VAL19:.*]] = tt.broadcast %[[VAL18]] : tensor<128x1xi1> -> tensor<128x128xi1>
// CHECK-DAG: %[[VAL20:.*]] = arith.cmpi sge, %[[VAL12]], %[[CST0]]
// CHECK-DAG: %[[VAL21:.*]] = arith.cmpi slt, %[[VAL12]], %[[CST3]]
// CHECK-DAG: %[[VAL22:.*]] = arith.andi %[[VAL20]], %[[VAL21]]
// CHECK-DAG: %[[VAL23:.*]] = tt.broadcast %[[VAL22]] : tensor<1x128xi1> -> tensor<128x128xi1>
// CHECK-DAG: %[[VAL24:.*]] = arith.andi %[[VAL19]], %[[VAL23]]

// CHECK-DAG: %[[VAL25:.*]] = tt.load %[[VAL15]], %[[VAL24]], %[[CST]]
// CHECK: tt.return %[[VAL25]] :

// -----

module {
  tt.func public @store(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: i32, %arg2: i32, %arg3: tensor<128x128xf32>) {
    %c1_i64 = arith.constant 1 : i64
    %c256_i64 = arith.constant 256 : i64
    %c0_i32 = arith.constant 0 : i32
    %c128_i32 = arith.constant 128 : i32
    %c256_i32 = arith.constant 256 : i32
    %0 = tt.make_tensor_descriptor %arg0, [%c256_i32, %c256_i32], [%c1_i64, %c256_i64] {order = array<i32: 0>} : <f32>, <128x128xf32>
    tt.descriptor_store %0[%arg1, %arg2], %arg3 : !tt.tensordesc<128x128xf32>, tensor<128x128xf32>
    tt.return
  }
}

// CHECK-LABEL: @store
// CHECK-SAME: %[[ARG0:[^:]*]]
// CHECK-SAME: %[[ARG1:[^:]*]]
// CHECK-SAME: %[[ARG2:[^:]*]]
// CHECK-SAME: %[[ARG3:[^:]*]]
// CHECK-DAG: %[[CST:.*]] = arith.constant dense<0> : tensor<1x128xi64>
// CHECK-DAG: %[[CST0:.*]] = arith.constant dense<256> : tensor<128x1xi64>
// CHECK-DAG: %[[CST1:.*]] = arith.constant dense<0> : tensor<128x1xi64>
// CHECK-DAG: %[[CST2:.*]] = arith.constant dense<256> : tensor<1x128xi64>

// CHECK-DAG: %[[VAL0:.*]] = arith.extsi %[[ARG1]] : i32 to i64
// CHECK-DAG: %[[VAL1:.*]] = arith.extsi %[[ARG2]] : i32 to i64
// CHECK-DAG: %[[VAL2:.*]] = tt.splat %[[ARG0]] :
// CHECK-DAG: %[[VAL3:.*]] = tt.splat %[[VAL0]] :
// CHECK-DAG: %[[VAL4:.*]] = tt.make_range {end = 128 : i32, start = 0 : i32}
// CHECK-DAG: %[[VAL5:.*]] = arith.extsi %[[VAL4]] :
// CHECK-DAG: %[[VAL6:.*]] = arith.addi %[[VAL3]], %[[VAL5]] :
// CHECK-DAG: %[[VAL7:.*]] = tt.reshape %[[VAL6]]
// CHECK-DAG: %[[VAL8:.*]] = tt.broadcast %[[VAL7]] : tensor<128x1xi64> -> tensor<128x128xi64>
// CHECK-DAG: %[[VAL9:.*]] = tt.addptr %[[VAL2]], %[[VAL8]] :
// CHECK-DAG: %[[VAL10:.*]] = tt.splat %[[VAL1]] :
// CHECK-DAG: %[[VAL11:.*]] = arith.addi %[[VAL10]], %[[VAL5]] :
// CHECK-DAG: %[[VAL12:.*]] = tt.reshape %[[VAL11]]
// CHECK-DAG: %[[VAL13:.*]] = arith.muli %[[VAL12]], %[[CST2]] :
// CHECK-DAG: %[[VAL14:.*]] = tt.broadcast %[[VAL13]] : tensor<1x128xi64> -> tensor<128x128xi64>
// CHECK-DAG: %[[VAL15:.*]] = tt.addptr %[[VAL9]], %[[VAL14]] :

// CHECK-DAG: %[[VAL16:.*]] = arith.cmpi sge, %[[VAL7]], %[[CST1]]
// CHECK-DAG: %[[VAL17:.*]] = arith.cmpi slt, %[[VAL7]], %[[CST0]]
// CHECK-DAG: %[[VAL18:.*]] = arith.andi %[[VAL16]], %[[VAL17]]
// CHECK-DAG: %[[VAL19:.*]] = tt.broadcast %[[VAL18]] : tensor<128x1xi1> -> tensor<128x128xi1>
// CHECK-DAG: %[[VAL20:.*]] = arith.cmpi sge, %[[VAL12]], %[[CST]]
// CHECK-DAG: %[[VAL21:.*]] = arith.cmpi slt, %[[VAL12]], %[[CST2]]
// CHECK-DAG: %[[VAL22:.*]] = arith.andi %[[VAL20]], %[[VAL21]]
// CHECK-DAG: %[[VAL23:.*]] = tt.broadcast %[[VAL22]] : tensor<1x128xi1> -> tensor<128x128xi1>
// CHECK-DAG: %[[VAL24:.*]] = arith.andi %[[VAL19]], %[[VAL23]]

// CHECK: tt.store %[[VAL15]], %[[ARG3]], %[[VAL24]]

// -----

module {
  tt.func public @scatter(%arg0: !tt.ptr<bf16> {tt.divisibility = 16 : i32}, %arg1: i32, %arg2: i32, %arg3: tensor<32xi32>, %arg4: tensor<32x128xbf16>) {
    %c1_i64 = arith.constant 1 : i64
    %c256_i64 = arith.constant 256 : i64
    %c256_i32 = arith.constant 256 : i32
    %c128_i32 = arith.constant 128 : i32
    %c8_i32 = arith.constant 8 : i32
    %0 = tt.make_tensor_descriptor %arg0, [%c256_i32, %c128_i32], [%c256_i64, %c1_i64] {order = array<i32: 0>} : <bf16>, <1x128xbf16>
    tt.descriptor_scatter %0[%arg3, %c8_i32], %arg4 : !tt.tensordesc<1x128xbf16>, tensor<32xi32>, i32, tensor<32x128xbf16>
    tt.return
  }
}

// CHECK-LABEL: @scatter
// CHECK-SAME: %[[ARG0:[^:]*]]
// CHECK-SAME: %[[ARG1:[^:]*]]
// CHECK-SAME: %[[ARG2:[^:]*]]
// CHECK-SAME: %[[ARG3:[^:]*]]
// CHECK-SAME: %[[ARG4:[^:]*]]
// CHECK-DAG: %[[CST:.*]] = arith.constant dense<128> : tensor<1x128xi64>
// CHECK-DAG: %[[CST0:.*]] = arith.constant dense<0> : tensor<1x128xi64>
// CHECK-DAG: %[[CST1:.*]] = arith.constant dense<0> : tensor<32x1xi64>
// CHECK-DAG: %[[CST2:.*]] = arith.constant dense<256> : tensor<32x1xi64>
// CHECK-DAG: %[[CST3:.*]] = arith.constant dense<8> : tensor<128xi64>

// CHECK-DAG: %[[VAL0:.*]] = tt.reshape %[[ARG3]] : tensor<32xi32> -> tensor<32x1xi32>
// CHECK-DAG: %[[VAL1:.*]] = arith.extsi %[[VAL0]] : tensor<32x1xi32> to tensor<32x1xi64>
// CHECK-DAG: %[[VAL2:.*]] = tt.make_range {end = 128 : i32, start = 0 : i32}
// CHECK-DAG: %[[VAL3:.*]] = arith.extsi %[[VAL2]] :
// CHECK-DAG: %[[VAL4:.*]] = arith.addi %[[VAL3]], %[[CST3]] : tensor<128xi64>
// CHECK-DAG: %[[VAL5:.*]] = tt.reshape %[[VAL4]] : tensor<128xi64> -> tensor<1x128xi64>
// CHECK-DAG: %[[VAL6:.*]] = tt.splat %[[ARG0]] :
// CHECK-DAG: %[[VAL7:.*]] = arith.muli %[[VAL1]], %[[CST2]] : tensor<32x1xi64>
// CHECK-DAG: %[[VAL8:.*]] = tt.broadcast %[[VAL7]] : tensor<32x1xi64> -> tensor<32x128xi64>
// CHECK-DAG: %[[VAL9:.*]] = tt.addptr %[[VAL6]], %[[VAL8]] :
// CHECK-DAG: %[[VAL10:.*]] = tt.broadcast %[[VAL5]] : tensor<1x128xi64> -> tensor<32x128xi64>
// CHECK-DAG: %[[VAL11:.*]] = tt.addptr %[[VAL9]], %[[VAL10]] :

// CHECK-DAG: %[[VAL12:.*]] = arith.cmpi sge, %[[VAL1]], %[[CST1]]
// CHECK-DAG: %[[VAL13:.*]] = arith.cmpi slt, %[[VAL1]], %[[CST2]]
// CHECK-DAG: %[[VAL14:.*]] = arith.andi %[[VAL12]], %[[VAL13]]
// CHECK-DAG: %[[VAL15:.*]] = tt.broadcast %[[VAL14]] : tensor<32x1xi1> -> tensor<32x128xi1>
// CHECK-DAG: %[[VAL16:.*]] = arith.cmpi sge, %[[VAL5]], %[[CST0]]
// CHECK-DAG: %[[VAL17:.*]] = arith.cmpi slt, %[[VAL5]], %[[CST]]
// CHECK-DAG: %[[VAL18:.*]] = arith.andi %[[VAL16]], %[[VAL17]]
// CHECK-DAG: %[[VAL19:.*]] = tt.broadcast %[[VAL18]] : tensor<1x128xi1> -> tensor<32x128xi1>
// CHECK-DAG: %[[VAL20:.*]] = arith.andi %[[VAL15]], %[[VAL19]]

// CHECK: tt.store %[[VAL11]], %[[ARG4]], %[[VAL20]]

// -----

#loc2 = loc("rewrite-tensor-descriptor-to-pointer.mlir":147:28)
module {
  tt.func public @callee(%tensordesc: !tt.tensordesc<128x128xf32> loc("tensordesc"(#loc2))) -> !tt.tensordesc<128x128xf32> {
    tt.return %tensordesc : !tt.tensordesc<128x128xf32>
  }

  tt.func public @caller(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}) {
    %c1_i64 = arith.constant 1 : i64
    %c256_i32 = arith.constant 256 : i32
    %c256_i64 = arith.constant 256 : i64
    %0 = tt.make_tensor_descriptor %arg0, [%c256_i32, %c256_i32], [%c256_i64, %c1_i64] {order = array<i32: 0>} : <f32>, <128x128xf32>
    %1 = tt.call @callee(%0) : (!tt.tensordesc<128x128xf32>) -> !tt.tensordesc<128x128xf32>
    tt.return
  }
}

// CHECK-LABEL: @callee
// CHECK-SAME: %[[PTR:[^:]*]]
// CHECK-SAME: loc("tensordesc"(#loc{{[^,]*}}))
// CHECK-SAME: %[[SHAPE0:[^:]*]]
// CHECK-SAME: loc("tensordesc.shape.0"(#loc{{[^,]*}}))
// CHECK-SAME: %[[SHAPE1:[^:]*]]
// CHECK-SAME: loc("tensordesc.shape.1"(#loc{{[^,]*}}))
// CHECK-SAME: %[[STRIDE0:[^:]*]]
// CHECK-SAME: loc("tensordesc.stride.0"(#loc{{[^,]*}}))
// CHECK-SAME: %[[STRIDE1:[^:]*]]
// CHECK-SAME: loc("tensordesc.stride.1"(#loc{{[^,]*}}))
// CHECK-SAME: %[[PAD:[^:]*]]
// CHECK-SAME: loc("tensordesc.padding"(#loc{{[^,]*}}))
// CHECK-SAME: %[[ROUND:[^:]*]]
// CHECK-SAME: loc("tensordesc.roundF32ToTF32"(#loc{{[^,]*}}))
// CHECK-NEXT: tt.return %[[PTR]], %[[SHAPE0]], %[[SHAPE1]], %[[STRIDE0]], %[[STRIDE1]], %[[PAD]], %[[ROUND]]

// CHECK-LABEL: @caller
// CHECK-SAME: %[[PTR:[^:]*]]
// CHECK-DAG: %[[c1:.*]] = arith.constant 1 : i64
// CHECK-DAG: %[[c256:.*]] = arith.constant 256 : i64
// CHECK: %{{.*}}:7 = tt.call @callee(%[[PTR]], %[[c256]], %[[c256]], %[[c256]], %[[c1]], %false, %false)
// CHECK-SAME -> (!tt.ptr<f32>, i64, i64, i64, i64, i1, i1)

// -----

module {
  tt.func public @arg_attr(%arg0: !tt.tensordesc<128x128xf32>, %arg1: i32 {tt.divisibility = 16 : i32}) {
    tt.return
  }
}

// CHECK-LABEL: @arg_attr
// CHECK-SAME: %arg7: i32 {tt.divisibility = 16 : i32} loc({{.*}})) {

// -----

module {
  tt.func public @reduce_add_i32(%base: !tt.ptr<i32>, %offset: i32, %src: tensor<16xi32>) {
    %c18_i32 = arith.constant 18 : i32
    %c1_i64 = arith.constant 1 : i64
    %desc = tt.make_tensor_descriptor %base, [%c18_i32], [%c1_i64] : <i32>, <16xi32>
    tt.descriptor_reduce add, %desc[%offset], %src : !tt.tensordesc<16xi32>, tensor<16xi32>
    tt.return
  }
}

// CHECK-LABEL: @reduce_add_i32
// CHECK-SAME: %[[BASE:[^:]*]]
// CHECK-SAME: %[[OFFSET:[^:]*]]
// CHECK-SAME: %[[SRC:[^:]*]]
// CHECK: %[[MASK:.*]] = arith.andi
// CHECK: tt.atomic_rmw add, release, gpu,
// CHECK-SAME: %[[SRC]], %[[MASK]]
