// RUN: env TRITON_METAL_SCALAR_DOT=1 triton-metal-opt --convert-tritongpu-to-metal %s | FileCheck %s
//
// Complex matmul correctness fallback for FFT-like kernels. The source loop
// carries four advancing pointers plus two f32 accumulators. Its body computes:
//   old_real + (dot(ar, br) - dot(ai, bi))
//   old_imag + (dot(ar, bi) + dot(ai, br))
// The Metal fallback proves that exact four-dot/two-accumulator structure and
// emits four scalar reductions before forming the two independent stores.
//
// CHECK-LABEL: metal.kernel complex_dot_kernel
// CHECK-COUNT-4: scf.for {{.*}} iter_args
// CHECK: metal.binary_exp {{.*}} subOp
// CHECK: metal.binary_exp {{.*}} addOp
// CHECK-COUNT-2: metal.store
// CHECK-NOT: tt.dot
// CHECK-NOT: ttg.convert_layout
//
#blocked = #ttg.blocked<{sizePerThread = [1, 1], threadsPerWarp = [4, 8], warpsPerCTA = [1, 1], order = [1, 0]}>
#loc = loc("/private/tmp/dump_complex_dot_ttgir.py":8:1)
#loc34 = loc("ar"(#loc))
#loc35 = loc("ai"(#loc))
#loc36 = loc("br"(#loc))
#loc37 = loc("bi"(#loc))
#loc38 = loc("cr"(#loc))
#loc39 = loc("ci"(#loc))
module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, ttg.target = "cuda:80", "ttg.threads-per-warp" = 32 : i32} {
  tt.func public @complex_dot_kernel(%ar: !tt.ptr<f32> loc("ar"(#loc)), %ai: !tt.ptr<f32> loc("ai"(#loc)), %br: !tt.ptr<f32> loc("br"(#loc)), %bi: !tt.ptr<f32> loc("bi"(#loc)), %cr: !tt.ptr<f32> loc("cr"(#loc)), %ci: !tt.ptr<f32> loc("ci"(#loc))) attributes {noinline = false} {
    %c8_i32 = arith.constant 8 : i32 loc(#loc1)
    %c16_i32 = arith.constant 16 : i32 loc(#loc2)
    %c0_i32 = arith.constant 0 : i32 loc(#loc2)
    %cst = arith.constant dense<128> : tensor<8x8xi32, #blocked> loc(#loc1)
    %cst_0 = arith.constant dense<8> : tensor<8x8xi32, #blocked> loc(#loc1)
    %cst_1 = arith.constant dense<0.000000e+00> : tensor<8x8xf32, #blocked> loc(#loc1)
    %cst_2 = arith.constant dense<16> : tensor<8x1xi32, #blocked> loc(#loc1)
    %pid_m = tt.get_program_id x : i32 loc(#loc40)
    %pid_n = tt.get_program_id y : i32 loc(#loc41)
    %offs_m = arith.muli %pid_m, %c8_i32 : i32 loc(#loc42)
    %offs_m_3 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32, #ttg.slice<{dim = 1, parent = #blocked}>> loc(#loc43)
    %offs_m_4 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32, #ttg.slice<{dim = 0, parent = #blocked}>> loc(#loc43)
    %offs_m_5 = tt.splat %offs_m : i32 -> tensor<8xi32, #ttg.slice<{dim = 1, parent = #blocked}>> loc(#loc42)
    %offs_m_6 = arith.addi %offs_m_5, %offs_m_3 : tensor<8xi32, #ttg.slice<{dim = 1, parent = #blocked}>> loc(#loc42)
    %offs_n = arith.muli %pid_n, %c8_i32 : i32 loc(#loc44)
    %offs_n_7 = tt.splat %offs_n : i32 -> tensor<8xi32, #ttg.slice<{dim = 0, parent = #blocked}>> loc(#loc44)
    %offs_n_8 = arith.addi %offs_n_7, %offs_m_4 : tensor<8xi32, #ttg.slice<{dim = 0, parent = #blocked}>> loc(#loc44)
    %a_ptrs = tt.expand_dims %offs_m_6 {axis = 1 : i32} : tensor<8xi32, #ttg.slice<{dim = 1, parent = #blocked}>> -> tensor<8x1xi32, #blocked> loc(#loc45)
    %a_ptrs_9 = arith.muli %a_ptrs, %cst_2 : tensor<8x1xi32, #blocked> loc(#loc45)
    %a_ptrs_10 = tt.splat %ar : !tt.ptr<f32> -> tensor<8x1x!tt.ptr<f32>, #blocked> loc(#loc46)
    %a_ptrs_11 = tt.addptr %a_ptrs_10, %a_ptrs_9 : tensor<8x1x!tt.ptr<f32>, #blocked>, tensor<8x1xi32, #blocked> loc(#loc46)
    %a_ptrs_12 = tt.expand_dims %offs_m_4 {axis = 0 : i32} : tensor<8xi32, #ttg.slice<{dim = 0, parent = #blocked}>> -> tensor<1x8xi32, #blocked> loc(#loc47)
    %a_ptrs_13 = tt.broadcast %a_ptrs_11 : tensor<8x1x!tt.ptr<f32>, #blocked> -> tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc46)
    %a_ptrs_14 = tt.broadcast %a_ptrs_12 : tensor<1x8xi32, #blocked> -> tensor<8x8xi32, #blocked> loc(#loc46)
    %a_ptrs_15 = tt.addptr %a_ptrs_13, %a_ptrs_14 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc46)
    %ai_ptrs = tt.splat %ai : !tt.ptr<f32> -> tensor<8x1x!tt.ptr<f32>, #blocked> loc(#loc48)
    %ai_ptrs_16 = tt.addptr %ai_ptrs, %a_ptrs_9 : tensor<8x1x!tt.ptr<f32>, #blocked>, tensor<8x1xi32, #blocked> loc(#loc48)
    %ai_ptrs_17 = tt.broadcast %ai_ptrs_16 : tensor<8x1x!tt.ptr<f32>, #blocked> -> tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc48)
    %ai_ptrs_18 = tt.addptr %ai_ptrs_17, %a_ptrs_14 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc48)
    %br_ptrs = tt.expand_dims %offs_m_3 {axis = 1 : i32} : tensor<8xi32, #ttg.slice<{dim = 1, parent = #blocked}>> -> tensor<8x1xi32, #blocked> loc(#loc49)
    %br_ptrs_19 = arith.muli %br_ptrs, %cst_2 : tensor<8x1xi32, #blocked> loc(#loc49)
    %br_ptrs_20 = tt.splat %br : !tt.ptr<f32> -> tensor<8x1x!tt.ptr<f32>, #blocked> loc(#loc50)
    %br_ptrs_21 = tt.addptr %br_ptrs_20, %br_ptrs_19 : tensor<8x1x!tt.ptr<f32>, #blocked>, tensor<8x1xi32, #blocked> loc(#loc50)
    %br_ptrs_22 = tt.expand_dims %offs_n_8 {axis = 0 : i32} : tensor<8xi32, #ttg.slice<{dim = 0, parent = #blocked}>> -> tensor<1x8xi32, #blocked> loc(#loc51)
    %br_ptrs_23 = tt.broadcast %br_ptrs_21 : tensor<8x1x!tt.ptr<f32>, #blocked> -> tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc50)
    %br_ptrs_24 = tt.broadcast %br_ptrs_22 : tensor<1x8xi32, #blocked> -> tensor<8x8xi32, #blocked> loc(#loc50)
    %br_ptrs_25 = tt.addptr %br_ptrs_23, %br_ptrs_24 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc50)
    %bi_ptrs = tt.splat %bi : !tt.ptr<f32> -> tensor<8x1x!tt.ptr<f32>, #blocked> loc(#loc52)
    %bi_ptrs_26 = tt.addptr %bi_ptrs, %br_ptrs_19 : tensor<8x1x!tt.ptr<f32>, #blocked>, tensor<8x1xi32, #blocked> loc(#loc52)
    %bi_ptrs_27 = tt.broadcast %bi_ptrs_26 : tensor<8x1x!tt.ptr<f32>, #blocked> -> tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc52)
    %bi_ptrs_28 = tt.addptr %bi_ptrs_27, %br_ptrs_24 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc52)
    %acc_i:6 = scf.for %_ = %c0_i32 to %c16_i32 step %c8_i32 iter_args(%a_ptrs_35 = %a_ptrs_15, %ai_ptrs_36 = %ai_ptrs_18, %br_ptrs_37 = %br_ptrs_25, %bi_ptrs_38 = %bi_ptrs_28, %acc_r = %cst_1, %acc_i_39 = %cst_1) -> (tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xf32, #blocked>, tensor<8x8xf32, #blocked>)  : i32 {
      %xr = tt.load %a_ptrs_35 : tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc54)
      %xi = tt.load %ai_ptrs_36 : tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc55)
      %wr = tt.load %br_ptrs_37 : tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc56)
      %wi = tt.load %bi_ptrs_38 : tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc57)
      %xr_40 = ttg.convert_layout %xr : tensor<8x8xf32, #blocked> -> tensor<8x8xf32, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> loc(#loc54)
      %wr_41 = ttg.convert_layout %wr : tensor<8x8xf32, #blocked> -> tensor<8x8xf32, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> loc(#loc56)
      %acc_r_42 = tt.dot %xr_40, %wr_41, %cst_1 : tensor<8x8xf32, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> * tensor<8x8xf32, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> -> tensor<8x8xf32, #blocked> loc(#loc58)
      %xi_43 = ttg.convert_layout %xi : tensor<8x8xf32, #blocked> -> tensor<8x8xf32, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> loc(#loc55)
      %wi_44 = ttg.convert_layout %wi : tensor<8x8xf32, #blocked> -> tensor<8x8xf32, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> loc(#loc57)
      %acc_r_45 = tt.dot %xi_43, %wi_44, %cst_1 : tensor<8x8xf32, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> * tensor<8x8xf32, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> -> tensor<8x8xf32, #blocked> loc(#loc59)
      %acc_r_46 = arith.subf %acc_r_42, %acc_r_45 : tensor<8x8xf32, #blocked> loc(#loc58)
      %acc_r_47 = arith.addf %acc_r, %acc_r_46 : tensor<8x8xf32, #blocked> loc(#loc60)
      %acc_i_48 = tt.dot %xr_40, %wi_44, %cst_1 : tensor<8x8xf32, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> * tensor<8x8xf32, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> -> tensor<8x8xf32, #blocked> loc(#loc61)
      %acc_i_49 = tt.dot %xi_43, %wr_41, %acc_i_48 : tensor<8x8xf32, #ttg.dot_op<{opIdx = 0, parent = #blocked}>> * tensor<8x8xf32, #ttg.dot_op<{opIdx = 1, parent = #blocked}>> -> tensor<8x8xf32, #blocked> loc(#loc62)
      %acc_i_50 = arith.addf %acc_i_39, %acc_i_49 : tensor<8x8xf32, #blocked> loc(#loc63)
      %a_ptrs_51 = tt.addptr %a_ptrs_35, %cst_0 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc64)
      %ai_ptrs_52 = tt.addptr %ai_ptrs_36, %cst_0 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc65)
      %br_ptrs_53 = tt.addptr %br_ptrs_37, %cst : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc66)
      %bi_ptrs_54 = tt.addptr %bi_ptrs_38, %cst : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc67)
      scf.yield %a_ptrs_51, %ai_ptrs_52, %br_ptrs_53, %bi_ptrs_54, %acc_r_47, %acc_i_50 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xf32, #blocked>, tensor<8x8xf32, #blocked> loc(#loc2)
    } loc(#loc74)
    %c_ptrs = tt.splat %cr : !tt.ptr<f32> -> tensor<8x1x!tt.ptr<f32>, #blocked> loc(#loc68)
    %c_ptrs_29 = tt.addptr %c_ptrs, %a_ptrs_9 : tensor<8x1x!tt.ptr<f32>, #blocked>, tensor<8x1xi32, #blocked> loc(#loc68)
    %c_ptrs_30 = tt.broadcast %c_ptrs_29 : tensor<8x1x!tt.ptr<f32>, #blocked> -> tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc68)
    %c_ptrs_31 = tt.addptr %c_ptrs_30, %br_ptrs_24 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc68)
    %ci_ptrs = tt.splat %ci : !tt.ptr<f32> -> tensor<8x1x!tt.ptr<f32>, #blocked> loc(#loc69)
    %ci_ptrs_32 = tt.addptr %ci_ptrs, %a_ptrs_9 : tensor<8x1x!tt.ptr<f32>, #blocked>, tensor<8x1xi32, #blocked> loc(#loc69)
    %ci_ptrs_33 = tt.broadcast %ci_ptrs_32 : tensor<8x1x!tt.ptr<f32>, #blocked> -> tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc69)
    %ci_ptrs_34 = tt.addptr %ci_ptrs_33, %br_ptrs_24 : tensor<8x8x!tt.ptr<f32>, #blocked>, tensor<8x8xi32, #blocked> loc(#loc69)
    tt.store %c_ptrs_31, %acc_i#4 : tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc32)
    tt.store %ci_ptrs_34, %acc_i#5 : tensor<8x8x!tt.ptr<f32>, #blocked> loc(#loc33)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/private/tmp/dump_complex_dot_ttgir.py":20:5)
#loc3 = loc("/private/tmp/dump_complex_dot_ttgir.py":9:13)
#loc4 = loc("/private/tmp/dump_complex_dot_ttgir.py":10:13)
#loc5 = loc("/private/tmp/dump_complex_dot_ttgir.py":11:14)
#loc6 = loc("/private/tmp/dump_complex_dot_ttgir.py":11:30)
#loc7 = loc("/private/tmp/dump_complex_dot_ttgir.py":12:14)
#loc8 = loc("/private/tmp/dump_complex_dot_ttgir.py":14:19)
#loc9 = loc("/private/tmp/dump_complex_dot_ttgir.py":14:14)
#loc10 = loc("/private/tmp/dump_complex_dot_ttgir.py":14:41)
#loc11 = loc("/private/tmp/dump_complex_dot_ttgir.py":15:15)
#loc12 = loc("/private/tmp/dump_complex_dot_ttgir.py":16:20)
#loc13 = loc("/private/tmp/dump_complex_dot_ttgir.py":16:15)
#loc14 = loc("/private/tmp/dump_complex_dot_ttgir.py":16:42)
#loc15 = loc("/private/tmp/dump_complex_dot_ttgir.py":17:15)
#loc16 = loc("/private/tmp/dump_complex_dot_ttgir.py":21:14)
#loc17 = loc("/private/tmp/dump_complex_dot_ttgir.py":22:14)
#loc18 = loc("/private/tmp/dump_complex_dot_ttgir.py":23:14)
#loc19 = loc("/private/tmp/dump_complex_dot_ttgir.py":24:14)
#loc20 = loc("/private/tmp/dump_complex_dot_ttgir.py":25:18)
#loc21 = loc("/private/tmp/dump_complex_dot_ttgir.py":25:35)
#loc22 = loc("/private/tmp/dump_complex_dot_ttgir.py":25:9)
#loc23 = loc("/private/tmp/dump_complex_dot_ttgir.py":26:18)
#loc24 = loc("/private/tmp/dump_complex_dot_ttgir.py":26:35)
#loc25 = loc("/private/tmp/dump_complex_dot_ttgir.py":26:9)
#loc26 = loc("/private/tmp/dump_complex_dot_ttgir.py":27:9)
#loc27 = loc("/private/tmp/dump_complex_dot_ttgir.py":28:9)
#loc28 = loc("/private/tmp/dump_complex_dot_ttgir.py":29:9)
#loc29 = loc("/private/tmp/dump_complex_dot_ttgir.py":30:9)
#loc30 = loc("/private/tmp/dump_complex_dot_ttgir.py":31:14)
#loc31 = loc("/private/tmp/dump_complex_dot_ttgir.py":32:15)
#loc32 = loc("/private/tmp/dump_complex_dot_ttgir.py":33:5)
#loc33 = loc("/private/tmp/dump_complex_dot_ttgir.py":34:5)
#loc40 = loc("pid_m"(#loc3))
#loc41 = loc("pid_n"(#loc4))
#loc42 = loc("offs_m"(#loc5))
#loc43 = loc("offs_m"(#loc6))
#loc44 = loc("offs_n"(#loc7))
#loc45 = loc("a_ptrs"(#loc8))
#loc46 = loc("a_ptrs"(#loc9))
#loc47 = loc("a_ptrs"(#loc10))
#loc48 = loc("ai_ptrs"(#loc11))
#loc49 = loc("br_ptrs"(#loc12))
#loc50 = loc("br_ptrs"(#loc13))
#loc51 = loc("br_ptrs"(#loc14))
#loc52 = loc("bi_ptrs"(#loc15))
#loc53 = loc("a_ptrs"(#loc2))
#loc54 = loc("xr"(#loc16))
#loc55 = loc("xi"(#loc17))
#loc56 = loc("wr"(#loc18))
#loc57 = loc("wi"(#loc19))
#loc58 = loc("acc_r"(#loc20))
#loc59 = loc("acc_r"(#loc21))
#loc60 = loc("acc_r"(#loc22))
#loc61 = loc("acc_i"(#loc23))
#loc62 = loc("acc_i"(#loc24))
#loc63 = loc("acc_i"(#loc25))
#loc64 = loc("a_ptrs"(#loc26))
#loc65 = loc("ai_ptrs"(#loc27))
#loc66 = loc("br_ptrs"(#loc28))
#loc67 = loc("bi_ptrs"(#loc29))
#loc68 = loc("c_ptrs"(#loc30))
#loc69 = loc("ci_ptrs"(#loc31))
#loc70 = loc("ai_ptrs"(#loc53))
#loc71 = loc("br_ptrs"(#loc70))
#loc72 = loc("bi_ptrs"(#loc71))
#loc73 = loc("acc_r"(#loc72))
#loc74 = loc("acc_i"(#loc73))
